base_model: SE6446/Kryten-3.2B-untrained
load_in_8bit: false
load_in_4bit: false
strict: false
push_dataset_to_hub:
datasets:
  - path: DKYoon/SlimPajama-6B
    type: text
dataset_prepared_path:
val_set_size: 0.05
lora_model_dir:
sequence_len: 2048
max_packed_sequence_len:
wandb_project:
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:
output_dir: ./base-out
gradient_accumulation_steps: 2
micro_batch_size: 2
num_epochs: 2
optimizer: adamw
torchdistx_path:
lr_scheduler: cosine
learning_rate: 4.0
train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: true
gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention: true
flash_attention:
gptq_groupsize:
gptq_model_v1:
warmup_steps: 10
eval_steps: 0.05
save_steps:
debug:
hub_model_id: SE6446/Kryten-3.2b-proofofconcept
hub_strategy: every_save
use_auth_token: true
deepspeed:
weight_decay: 0.1
fsdp:
fsdp_config:
special_tokens:
  pad_token: "<|endoftext|>"